module.exports = {
  CustomerModel: require("./Customer"),
  ProducerModel: require("./Producer"),
  AddressModel: require("./Address"),
  ProductModel: require("./Product"),
  CurrencyModel: require("./Currency"),
  ChargeModel: require("./Charge"),
  OrderModel: require("./Order"),
  OrderDetailsModel: require("./OrderDetails"),
  SkuGalleryModel: require("./SkuGallery"),
  FaqModel: require("./Faq"),
  NotificationModel: require("./Notification"),
  OfferModel: require("./Offer"),
  ReviewModel: require("./Review"),
  ReturnPolicyModel: require("./ReturnPolicy"),
  EstimatedPickupLookup: require("./EstimatedPickupLookup"),
  ReasonLookup: require("./ReasonLookup"),
  ReturnReplaceItem: require("./ReturnReplaceItem"),
  // AdminModel: require('./Admin'),
};
